runtime: python312

automatic_scaling:
  max_instances: 2
  max_idle_instances: 1
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
  max_concurrent_requests: 50
  min_pending_latency: 500ms

entrypoint: gunicorn -b :$PORT -k gevent -w 1 'vimhelp.webapp:create_app()'

inbound_services:
- warmup

handlers:
- url: /.*
  script: auto
  secure: always
