runtime: python311

automatic_scaling:
  max_instances: 2
  max_idle_instances: 1
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
  max_concurrent_requests: 50
  min_pending_latency: 500ms

entrypoint: gunicorn -b :$PORT -k gevent -w 1 'vimhelp.webapp:create_app()'

default_expiration: "1h"

inbound_services:
- warmup

handlers:
- url: /(?:.*\.html)?
  script: auto
  secure: always
- url: /api/.+
  script: auto
  secure: always
- url: /(?:robots|sitemap)\.txt
  script: auto
  secure: always
- url: /s/.+
  script: auto
  secure: always
- url: /favicon\.ico
  script: auto
  secure: always
- url: /(?:enqueue_)?(?:update|clean_assets)
  script: auto
  secure: always
- url: /_ah/warmup
  script: auto
  secure: always
- url: /(.+)
  static_files: static/\1
  upload: static/(.*)
  secure: always
